server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    accesslog:
      enabled: true
      directory: ${logging.file.path}
      pattern: "%h %l %u %t %r %s %b %D"

spring:
  application:
    name: sysadmin
  profiles:
    active: dev
  security:
    mfa: false

logging:
  level:
    com.baomidou: debug
  file:
    name: ${spring.application.name}
    path: logs
  config: classpath:log4j2-dev.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.houtu.mp.module.sys.entity
  global-config:
    db-config:
      id-type: auto
      table-underline: true